[package]
name = "graham2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.19.1"
gtk = { version = "0.6.2", package = "gtk4", features = ["v4_10"] }
